name: CI/CD Pipeline

on:
  push:
    branches:
      - main1          # Trigger workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Backend with Maven
        run: |
          cd backend
          ./mvnw -B package --file pom.xml

      - name: Build Frontend with NPM
        run: |
          cd frontend
          npm install
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Backend Docker Image
        env:
          REGISTRY: ${{ secrets.AWS_REGISTRY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd backend
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx build --platform linux/amd64 -t $REGISTRY/backend:latest .
          docker login -u AWS -p $AWS_ACCESS_KEY_ID -e none $REGISTRY
          docker push $REGISTRY/backend:latest

      - name: Build and Push Frontend Docker Image
        env:
          REGISTRY: ${{ secrets.AWS_REGISTRY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd frontend
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx build --platform linux/amd64 -t $REGISTRY/frontend:latest .
          docker login -u AWS -p $AWS_ACCESS_KEY_ID -e none $REGISTRY
          docker push $REGISTRY/frontend:latest

      - name: Deploy to AWS EKS
        uses: appleboy/kubernetes-action@master
        with:
          kube_config_data: ${{ secrets.KUBE_CONFIG }}
          namespace: default
          manifests: kubernetes/
